name: CD
on:
  push:
    branches:
      - main
jobs:
  # tests:
  #   uses: ./.github/workflows/test.yml
  cd:
    name: CD
    # needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true
          cache: 'pnpm'
      - shell: bash
        run: pnpm i
      - name: Build
        run: pnpm -r build
      - name: Publish
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
